spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:7999/realms/FreeBoard}
          jwk-set-uri: ${KEYCLOAK_JWT_SET_URL:http://localhost:7999/realms/FreeBoard/protocol/openid-connect/certs}

  application:
    name: FreeBoard-EventHandler-Spring
  rsocket:
    server:
      port: ${RSOCKER_SERVER_PORT:7001}
      transport: websocket
      mapping-path: ${RSOCKER_PATH:/rsocket}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST:localhost}:9092
server:
  port: ${SERVER_PORT:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus, rsocket
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    enable:
      rsocket: true
  prometheus:
    metrics:
      export:
        enabled: true

api:
  auth:
    path: http://${AUTH_SERVICE_HOST:localhost}:${PROFILE_SERVICE_PORT:8080}/
  profile:
    path: http://${PROFILE_SERVICE_HOST:localhost}:${PROFILE_SERVICE_PORT:8081}/