spring:
  application:
    name: FreeBoard-EventHandler-Spring
  rsocket:
    server:
      port: ${RSOCKER_SERVER_PORT:7001}
      transport: websocket
      mapping-path: ${RSOCKER_PATH:/rsocket}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST:localhost}:9092
server:
  port: ${SERVER_PORT:8085}

jwt:
  secret-key: e3f7e72a3b6945d8b519b0c2358b9454f0334b2c0b6e3d6db5b44c6be7413b8f

api:
  auth:
    path: http://${AUTH_SERVICE_HOST:localhost}:${PROFILE_SERVICE_PORT:8080}/
  profile:
    path: http://${PROFILE_SERVICE_HOST:localhost}:${PROFILE_SERVICE_PORT:8081}/